---
title: "Assignments"
author: "Anton Holm"
date: '2020-09-16'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(mice)

```

#3.1
```{r}
Placebo <- data.frame(Time = c(1,1,2,2,3,4,4,5,5,8,8,8,8,11,11,12,12,15,17,22,23), event = 1, Method = "Placebo")
Six_MP <- data.frame(Time = c(6,6,6,6,7,9,10,10,11,13,16,17,19,20,22,23,25,32,32,34,35), event = c(1,1,1,0,1,0,1,0,0,1,1,0,0,0,1,1,0,0,0,0,0), Method = "6-MP")

Placebo_NA <- Placebo %>% 
  mutate(NA_est = nelsonaalen(Placebo, Time, event))


Six_MP_NA <- Six_MP %>% 
  mutate(NA_est = nelsonaalen(Six_MP, Time, event))

Both_Methods <- full_join(Placebo_NA, Six_MP_NA)

Both_Methods %>% 
  ggplot(aes(x = Time, y = NA_est, col = Method)) +
  geom_line() +
  labs(title = "Figure 1: Plot of Nelson-Aalen estimates for Ex 3.1")
```



#3.4

```{r}
Time_PB = c(1,2,3,4,5,8,11,12,15,17,22,23)
Risk_PB = c(19, 17, 16, 14, 12, 8, 6, 4, 3, 2, 1)
Ties_PB = c(2, 2, 1, 2, 2, 4, 2, 2, 1, 1, 1)
NA_est_PB = cumsum(Ties_PB/Risk_PB)

Time_MP = c(0,6,7,10,13,16,22,23)
Risk_MP = c(17,16,13,11,10,6,5)
Ties_MP = c(3,1,1,1,1,1,1)
NA_est_MP = cumsum(Ties_MP/Risk_MP)



KM_est_PB = c(1, cumprod(1- Ties_PB/Risk_PB))
KM_est_MP = c(1, cumprod(1- Ties_MP/Risk_MP))

plot(x = Time_PB, y = KM_est_PB, type = 's', main = "Figure 2: K-M estimates of Placebo(Black) and 6-MP(Blue)")
lines(x = Time_MP, y = KM_est_MP, type = 's', col = "blue")
```
